modLoader="javafml"
loaderVersion="[41,)"
license="All Rights Reserved unless otherwise explicitly stated"

[[mods]]
modId="beyond_addon"
version="1.0"
displayName="Beyond Addon"
displayURL="https://www.curseforge.com/minecraft/mc-mods/beyond-earth"
logoFile="logo.png"
authors="MrScautHD"
description='''
This Mod is a Addon for Beyond Earth!
'''

[[dependencies.beyond_addon]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19]"
    ordering="NONE"
    side="BOTH"

[[dependencies.beyond_addon]]
    modId="forge"
    mandatory=true
    versionRange="[41.0.100,]"
    ordering="NONE"
    side="BOTH"